//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeDiscovery.AccelerationModel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.teco.edu/AccelerationService", ConfigurationName="AccelerationModel.AccelerationService", CallbackContract=typeof(NodeDiscovery.AccelerationModel.AccelerationServiceCallback))]
    public interface AccelerationService {
        
        // CODEGEN: Generating message contract since the operation StartLDC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.teco.edu/AccelerationService/StartLDCIn", ReplyAction="http://www.teco.edu/AccelerationService/StartLDCOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.AccelerationModel.StartLDCResponse StartLDC(NodeDiscovery.AccelerationModel.StartLDCRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccelerationServiceCallback {
        
        // CODEGEN: Generating message contract since the operation AccelerationServiceEvent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.teco.edu/AccelerationService/AccelerationServiceEventOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AccelerationServiceEvent(NodeDiscovery.AccelerationModel.AccelerationServiceEvent request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/AccelerationService")]
    public partial class AccelerationSeries : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string deltaField;
        
        private AccelerationSample[] sampleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=2)]
        public string delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
                this.RaisePropertyChanged("delta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample", Order=3)]
        public AccelerationSample[] sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
                this.RaisePropertyChanged("sample");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/AccelerationService")]
    public partial class AccelerationSample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deltaField;
        
        private ADXL210_Sample acclField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=0)]
        public string delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
                this.RaisePropertyChanged("delta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ADXL210_Sample accl {
            get {
                return this.acclField;
            }
            set {
                this.acclField = value;
                this.RaisePropertyChanged("accl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/AccelerationService")]
    public partial class ADXL210_Sample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
                this.RaisePropertyChanged("z");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/AccelerationService")]
    public partial class LDCInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LDCInfoRate rateField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LDCInfoRate rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.teco.edu/AccelerationService")]
    public enum LDCInfoRate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("500")]
        Item500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("250")]
        Item250,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/2")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/5")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/10")]
        Item110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/30")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/60")]
        Item160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/120")]
        Item1120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/300")]
        Item1300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/600")]
        Item1600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/1800")]
        Item11800,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/3600")]
        Item13600,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccelerationServiceEvent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/AccelerationService", Order=0)]
        public NodeDiscovery.AccelerationModel.AccelerationSeries series;
        
        public AccelerationServiceEvent() {
        }
        
        public AccelerationServiceEvent(NodeDiscovery.AccelerationModel.AccelerationSeries series) {
            this.series = series;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLDCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/AccelerationService", Order=0)]
        public NodeDiscovery.AccelerationModel.LDCInfo ldcinfo;
        
        public StartLDCRequest() {
        }
        
        public StartLDCRequest(NodeDiscovery.AccelerationModel.LDCInfo ldcinfo) {
            this.ldcinfo = ldcinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLDCResponse {
        
        public StartLDCResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccelerationServiceChannel : NodeDiscovery.AccelerationModel.AccelerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccelerationServiceClient : System.ServiceModel.DuplexClientBase<NodeDiscovery.AccelerationModel.AccelerationService>, NodeDiscovery.AccelerationModel.AccelerationService {
        
        public AccelerationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AccelerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AccelerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AccelerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AccelerationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.AccelerationModel.StartLDCResponse NodeDiscovery.AccelerationModel.AccelerationService.StartLDC(NodeDiscovery.AccelerationModel.StartLDCRequest request) {
            return base.Channel.StartLDC(request);
        }
        
        public void StartLDC(NodeDiscovery.AccelerationModel.LDCInfo ldcinfo) {
            NodeDiscovery.AccelerationModel.StartLDCRequest inValue = new NodeDiscovery.AccelerationModel.StartLDCRequest();
            inValue.ldcinfo = ldcinfo;
            NodeDiscovery.AccelerationModel.StartLDCResponse retVal = ((NodeDiscovery.AccelerationModel.AccelerationService)(this)).StartLDC(inValue);
        }
    }
}
