//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeDiscovery.VLinkDataLogging {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService", ConfigurationName="VLinkDataLogging.DataLoggingService", CallbackContract=typeof(NodeDiscovery.VLinkDataLogging.DataLoggingServiceCallback))]
    public interface DataLoggingService {
        
        // CODEGEN: Generating message contract since the operation StartLogging is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.teco.edu/VLink/DataLoggingService/StartLoggingIn", ReplyAction="http://www.teco.edu/VLink/DataLoggingService/StartLoggingOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.VLinkDataLogging.StartLoggingResponse StartLogging(NodeDiscovery.VLinkDataLogging.StartLoggingRequest request);
        
        // CODEGEN: Generating message contract since the operation StartDownload is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.teco.edu/VLink/DataLoggingService/StartDownloadIn", ReplyAction="http://www.teco.edu/VLink/DataLoggingService/StartDownloadOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.VLinkDataLogging.StartDownloadResponse StartDownload(NodeDiscovery.VLinkDataLogging.StartDownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation Erase is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.teco.edu/VLink/DataLoggingService/EraseIn", ReplyAction="http://www.teco.edu/VLink/DataLoggingService/EraseOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.VLinkDataLogging.EraseResponse Erase(NodeDiscovery.VLinkDataLogging.EraseRequest request);
        
        // CODEGEN: Generating message contract since the operation GetSessionCount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.teco.edu/VLink/DataLoggingService/GetSessionCountIn", ReplyAction="http://www.teco.edu/VLink/DataLoggingService/GetSessionCountOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.VLinkDataLogging.GetSessionCountResponse GetSessionCount(NodeDiscovery.VLinkDataLogging.GetSessionCountRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataLoggingServiceCallback {
        
        // CODEGEN: Generating message contract since the operation DataLoggingServiceEvent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.teco.edu/VLink/DataLoggingService/DataLoggingServiceEventOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DataLoggingServiceEvent(NodeDiscovery.VLinkDataLogging.DataLoggingServiceEvent request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService")]
    public partial class MeasurementSeries : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string deltaField;
        
        private Sample[] sampleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=2)]
        public string delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
                this.RaisePropertyChanged("delta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample", Order=3)]
        public Sample[] sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
                this.RaisePropertyChanged("sample");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService")]
    public partial class Sample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deltaField;
        
        private float differential1Field;
        
        private bool differential1FieldSpecified;
        
        private float differential2Field;
        
        private bool differential2FieldSpecified;
        
        private float differential3Field;
        
        private bool differential3FieldSpecified;
        
        private float differential4Field;
        
        private bool differential4FieldSpecified;
        
        private float single1Field;
        
        private bool single1FieldSpecified;
        
        private float single2Field;
        
        private bool single2FieldSpecified;
        
        private float single3Field;
        
        private bool single3FieldSpecified;
        
        private float temperatureField;
        
        private bool temperatureFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=0)]
        public string delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
                this.RaisePropertyChanged("delta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float differential1 {
            get {
                return this.differential1Field;
            }
            set {
                this.differential1Field = value;
                this.RaisePropertyChanged("differential1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential1Specified {
            get {
                return this.differential1FieldSpecified;
            }
            set {
                this.differential1FieldSpecified = value;
                this.RaisePropertyChanged("differential1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float differential2 {
            get {
                return this.differential2Field;
            }
            set {
                this.differential2Field = value;
                this.RaisePropertyChanged("differential2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential2Specified {
            get {
                return this.differential2FieldSpecified;
            }
            set {
                this.differential2FieldSpecified = value;
                this.RaisePropertyChanged("differential2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float differential3 {
            get {
                return this.differential3Field;
            }
            set {
                this.differential3Field = value;
                this.RaisePropertyChanged("differential3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential3Specified {
            get {
                return this.differential3FieldSpecified;
            }
            set {
                this.differential3FieldSpecified = value;
                this.RaisePropertyChanged("differential3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float differential4 {
            get {
                return this.differential4Field;
            }
            set {
                this.differential4Field = value;
                this.RaisePropertyChanged("differential4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential4Specified {
            get {
                return this.differential4FieldSpecified;
            }
            set {
                this.differential4FieldSpecified = value;
                this.RaisePropertyChanged("differential4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float single1 {
            get {
                return this.single1Field;
            }
            set {
                this.single1Field = value;
                this.RaisePropertyChanged("single1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool single1Specified {
            get {
                return this.single1FieldSpecified;
            }
            set {
                this.single1FieldSpecified = value;
                this.RaisePropertyChanged("single1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float single2 {
            get {
                return this.single2Field;
            }
            set {
                this.single2Field = value;
                this.RaisePropertyChanged("single2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool single2Specified {
            get {
                return this.single2FieldSpecified;
            }
            set {
                this.single2FieldSpecified = value;
                this.RaisePropertyChanged("single2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float single3 {
            get {
                return this.single3Field;
            }
            set {
                this.single3Field = value;
                this.RaisePropertyChanged("single3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool single3Specified {
            get {
                return this.single3FieldSpecified;
            }
            set {
                this.single3FieldSpecified = value;
                this.RaisePropertyChanged("single3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
                this.RaisePropertyChanged("temperature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool temperatureSpecified {
            get {
                return this.temperatureFieldSpecified;
            }
            set {
                this.temperatureFieldSpecified = value;
                this.RaisePropertyChanged("temperatureSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService")]
    public partial class SessionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService")]
    public partial class LoggingConfig : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LoggingConfigRate rateField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LoggingConfigRate rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.teco.edu/VLink/DataLoggingService")]
    public enum LoggingConfigRate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2048")]
        Item2048,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1024")]
        Item1024,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("512")]
        Item512,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("256")]
        Item256,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("128")]
        Item128,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataLoggingServiceEvent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService", Order=0)]
        public NodeDiscovery.VLinkDataLogging.MeasurementSeries series;
        
        public DataLoggingServiceEvent() {
        }
        
        public DataLoggingServiceEvent(NodeDiscovery.VLinkDataLogging.MeasurementSeries series) {
            this.series = series;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLoggingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService", Order=0)]
        public NodeDiscovery.VLinkDataLogging.LoggingConfig loggingconfig;
        
        public StartLoggingRequest() {
        }
        
        public StartLoggingRequest(NodeDiscovery.VLinkDataLogging.LoggingConfig loggingconfig) {
            this.loggingconfig = loggingconfig;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLoggingResponse {
        
        public StartLoggingResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartDownloadRequest {
        
        public StartDownloadRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartDownloadResponse {
        
        public StartDownloadResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EraseRequest {
        
        public EraseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EraseResponse {
        
        public EraseResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionCountRequest {
        
        public GetSessionCountRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/VLink/DataLoggingService", Order=0)]
        public NodeDiscovery.VLinkDataLogging.SessionInfo sessioninfo;
        
        public GetSessionCountResponse() {
        }
        
        public GetSessionCountResponse(NodeDiscovery.VLinkDataLogging.SessionInfo sessioninfo) {
            this.sessioninfo = sessioninfo;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataLoggingServiceChannel : NodeDiscovery.VLinkDataLogging.DataLoggingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataLoggingServiceClient : System.ServiceModel.DuplexClientBase<NodeDiscovery.VLinkDataLogging.DataLoggingService>, NodeDiscovery.VLinkDataLogging.DataLoggingService {
        
        public DataLoggingServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DataLoggingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DataLoggingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataLoggingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DataLoggingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.VLinkDataLogging.StartLoggingResponse NodeDiscovery.VLinkDataLogging.DataLoggingService.StartLogging(NodeDiscovery.VLinkDataLogging.StartLoggingRequest request) {
            return base.Channel.StartLogging(request);
        }
        
        public void StartLogging(NodeDiscovery.VLinkDataLogging.LoggingConfig loggingconfig) {
            NodeDiscovery.VLinkDataLogging.StartLoggingRequest inValue = new NodeDiscovery.VLinkDataLogging.StartLoggingRequest();
            inValue.loggingconfig = loggingconfig;
            NodeDiscovery.VLinkDataLogging.StartLoggingResponse retVal = ((NodeDiscovery.VLinkDataLogging.DataLoggingService)(this)).StartLogging(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.VLinkDataLogging.StartDownloadResponse NodeDiscovery.VLinkDataLogging.DataLoggingService.StartDownload(NodeDiscovery.VLinkDataLogging.StartDownloadRequest request) {
            return base.Channel.StartDownload(request);
        }
        
        public void StartDownload() {
            NodeDiscovery.VLinkDataLogging.StartDownloadRequest inValue = new NodeDiscovery.VLinkDataLogging.StartDownloadRequest();
            NodeDiscovery.VLinkDataLogging.StartDownloadResponse retVal = ((NodeDiscovery.VLinkDataLogging.DataLoggingService)(this)).StartDownload(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.VLinkDataLogging.EraseResponse NodeDiscovery.VLinkDataLogging.DataLoggingService.Erase(NodeDiscovery.VLinkDataLogging.EraseRequest request) {
            return base.Channel.Erase(request);
        }
        
        public void Erase() {
            NodeDiscovery.VLinkDataLogging.EraseRequest inValue = new NodeDiscovery.VLinkDataLogging.EraseRequest();
            NodeDiscovery.VLinkDataLogging.EraseResponse retVal = ((NodeDiscovery.VLinkDataLogging.DataLoggingService)(this)).Erase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.VLinkDataLogging.GetSessionCountResponse NodeDiscovery.VLinkDataLogging.DataLoggingService.GetSessionCount(NodeDiscovery.VLinkDataLogging.GetSessionCountRequest request) {
            return base.Channel.GetSessionCount(request);
        }
        
        public NodeDiscovery.VLinkDataLogging.SessionInfo GetSessionCount() {
            NodeDiscovery.VLinkDataLogging.GetSessionCountRequest inValue = new NodeDiscovery.VLinkDataLogging.GetSessionCountRequest();
            NodeDiscovery.VLinkDataLogging.GetSessionCountResponse retVal = ((NodeDiscovery.VLinkDataLogging.DataLoggingService)(this)).GetSessionCount(inValue);
            return retVal.sessioninfo;
        }
    }
}
