//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeDiscovery.VLinkStreaming {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.teco.edu/VLink/StreamingService", ConfigurationName="VLinkStreaming.StreamingService", CallbackContract=typeof(NodeDiscovery.VLinkStreaming.StreamingServiceCallback))]
    public interface StreamingService {
        
        // CODEGEN: Generating message contract since the operation StartLDC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.teco.edu/VLink/StreamingService/StartLDCIn", ReplyAction="http://www.teco.edu/VLink/StreamingService/StartLDCOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.VLinkStreaming.StartLDCResponse StartLDC(NodeDiscovery.VLinkStreaming.StartLDCRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StreamingServiceCallback {
        
        // CODEGEN: Generating message contract since the operation StreamingServiceEvent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://www.teco.edu/VLink/StreamingService/StreamingServiceEventOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StreamingServiceEvent(NodeDiscovery.VLinkStreaming.StreamingServiceEvent request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/StreamingService")]
    public partial class MeasurementSeries : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string deltaField;
        
        private Sample[] sampleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=2)]
        public string delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
                this.RaisePropertyChanged("delta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample", Order=3)]
        public Sample[] sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
                this.RaisePropertyChanged("sample");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/StreamingService")]
    public partial class Sample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deltaField;
        
        private float differential1Field;
        
        private bool differential1FieldSpecified;
        
        private float differential2Field;
        
        private bool differential2FieldSpecified;
        
        private float differential3Field;
        
        private bool differential3FieldSpecified;
        
        private float differential4Field;
        
        private bool differential4FieldSpecified;
        
        private float single1Field;
        
        private bool single1FieldSpecified;
        
        private float single2Field;
        
        private bool single2FieldSpecified;
        
        private float single3Field;
        
        private bool single3FieldSpecified;
        
        private float temperatureField;
        
        private bool temperatureFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=0)]
        public string delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
                this.RaisePropertyChanged("delta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float differential1 {
            get {
                return this.differential1Field;
            }
            set {
                this.differential1Field = value;
                this.RaisePropertyChanged("differential1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential1Specified {
            get {
                return this.differential1FieldSpecified;
            }
            set {
                this.differential1FieldSpecified = value;
                this.RaisePropertyChanged("differential1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float differential2 {
            get {
                return this.differential2Field;
            }
            set {
                this.differential2Field = value;
                this.RaisePropertyChanged("differential2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential2Specified {
            get {
                return this.differential2FieldSpecified;
            }
            set {
                this.differential2FieldSpecified = value;
                this.RaisePropertyChanged("differential2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public float differential3 {
            get {
                return this.differential3Field;
            }
            set {
                this.differential3Field = value;
                this.RaisePropertyChanged("differential3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential3Specified {
            get {
                return this.differential3FieldSpecified;
            }
            set {
                this.differential3FieldSpecified = value;
                this.RaisePropertyChanged("differential3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float differential4 {
            get {
                return this.differential4Field;
            }
            set {
                this.differential4Field = value;
                this.RaisePropertyChanged("differential4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool differential4Specified {
            get {
                return this.differential4FieldSpecified;
            }
            set {
                this.differential4FieldSpecified = value;
                this.RaisePropertyChanged("differential4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public float single1 {
            get {
                return this.single1Field;
            }
            set {
                this.single1Field = value;
                this.RaisePropertyChanged("single1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool single1Specified {
            get {
                return this.single1FieldSpecified;
            }
            set {
                this.single1FieldSpecified = value;
                this.RaisePropertyChanged("single1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float single2 {
            get {
                return this.single2Field;
            }
            set {
                this.single2Field = value;
                this.RaisePropertyChanged("single2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool single2Specified {
            get {
                return this.single2FieldSpecified;
            }
            set {
                this.single2FieldSpecified = value;
                this.RaisePropertyChanged("single2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float single3 {
            get {
                return this.single3Field;
            }
            set {
                this.single3Field = value;
                this.RaisePropertyChanged("single3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool single3Specified {
            get {
                return this.single3FieldSpecified;
            }
            set {
                this.single3FieldSpecified = value;
                this.RaisePropertyChanged("single3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
                this.RaisePropertyChanged("temperature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool temperatureSpecified {
            get {
                return this.temperatureFieldSpecified;
            }
            set {
                this.temperatureFieldSpecified = value;
                this.RaisePropertyChanged("temperatureSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.teco.edu/VLink/StreamingService")]
    public partial class LDCInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LDCInfoRate rateField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LDCInfoRate rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
                this.RaisePropertyChanged("rate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.teco.edu/VLink/StreamingService")]
    public enum LDCInfoRate {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("500")]
        Item500,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("250")]
        Item250,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/2")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/5")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/10")]
        Item110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/30")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/60")]
        Item160,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/120")]
        Item1120,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/300")]
        Item1300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/600")]
        Item1600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/1800")]
        Item11800,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1/3600")]
        Item13600,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StreamingServiceEvent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/VLink/StreamingService", Order=0)]
        public NodeDiscovery.VLinkStreaming.MeasurementSeries series;
        
        public StreamingServiceEvent() {
        }
        
        public StreamingServiceEvent(NodeDiscovery.VLinkStreaming.MeasurementSeries series) {
            this.series = series;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLDCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.teco.edu/VLink/StreamingService", Order=0)]
        public NodeDiscovery.VLinkStreaming.LDCInfo ldcinfo;
        
        public StartLDCRequest() {
        }
        
        public StartLDCRequest(NodeDiscovery.VLinkStreaming.LDCInfo ldcinfo) {
            this.ldcinfo = ldcinfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLDCResponse {
        
        public StartLDCResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StreamingServiceChannel : NodeDiscovery.VLinkStreaming.StreamingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamingServiceClient : System.ServiceModel.DuplexClientBase<NodeDiscovery.VLinkStreaming.StreamingService>, NodeDiscovery.VLinkStreaming.StreamingService {
        
        public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StreamingServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.VLinkStreaming.StartLDCResponse NodeDiscovery.VLinkStreaming.StreamingService.StartLDC(NodeDiscovery.VLinkStreaming.StartLDCRequest request) {
            return base.Channel.StartLDC(request);
        }
        
        public void StartLDC(NodeDiscovery.VLinkStreaming.LDCInfo ldcinfo) {
            NodeDiscovery.VLinkStreaming.StartLDCRequest inValue = new NodeDiscovery.VLinkStreaming.StartLDCRequest();
            inValue.ldcinfo = ldcinfo;
            NodeDiscovery.VLinkStreaming.StartLDCResponse retVal = ((NodeDiscovery.VLinkStreaming.StreamingService)(this)).StartLDC(inValue);
        }
    }
}
