//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodeDiscovery.SensorValuesFH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues", ConfigurationName="SensorValuesFH.SensorValues")]
    public interface SensorValues {
        
        // CODEGEN: Generating message contract since the operation GetSensorValues is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues/GetSensorValuesIn", ReplyAction="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues/GetSensorValuesOut")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.SensorValuesFH.GetSensorValuesResponse GetSensorValues(NodeDiscovery.SensorValuesFH.GetSensorValuesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetConfig is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues/GetConfigRequest", ReplyAction="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues/GetConfigResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.SensorValuesFH.GetConfigResponse GetConfig(NodeDiscovery.SensorValuesFH.GetConfigRequest request);
        
        // CODEGEN: Generating message contract since the operation SetConfig is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues/SetConfigRequest", ReplyAction="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues/SetConfigResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NodeDiscovery.SensorValuesFH.GetConfigResponse SetConfig(NodeDiscovery.SensorValuesFH.SetConfigRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues")]
    public partial class Series : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        private Sample[] sampleField;
        
        private Fragment fragmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
                this.RaisePropertyChanged("timeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample", Order=1)]
        public Sample[] sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
                this.RaisePropertyChanged("sample");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Fragment fragment {
            get {
                return this.fragmentField;
            }
            set {
                this.fragmentField = value;
                this.RaisePropertyChanged("fragment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues")]
    public partial class Sample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SHT7x_Sample temperatureField;
        
        private string delta_tField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SHT7x_Sample Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
                this.RaisePropertyChanged("Temperature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=1)]
        public string delta_t {
            get {
                return this.delta_tField;
            }
            set {
                this.delta_tField = value;
                this.RaisePropertyChanged("delta_t");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues")]
    public partial class SHT7x_Sample : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SensorConfigurationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues")]
    public partial class Configuration : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues")]
    public partial class SensorConfigurationType : Configuration {
        
        private System.Xml.XmlElement anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues")]
    public partial class Fragment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte countField;
        
        private bool countFieldSpecified;
        
        private string delta_tField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public sbyte count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=1)]
        public string delta_t {
            get {
                return this.delta_tField;
            }
            set {
                this.delta_tField = value;
                this.RaisePropertyChanged("delta_t");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSensorValuesRequest {
        
        public GetSensorValuesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSensorValuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues", Order=0)]
        public NodeDiscovery.SensorValuesFH.Series Series;
        
        public GetSensorValuesResponse() {
        }
        
        public GetSensorValuesResponse(NodeDiscovery.SensorValuesFH.Series Series) {
            this.Series = Series;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigRequest {
        
        public GetConfigRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues", Order=0)]
        public NodeDiscovery.SensorValuesFH.Configuration Config;
        
        public GetConfigResponse() {
        }
        
        public GetConfigResponse(NodeDiscovery.SensorValuesFH.Configuration Config) {
            this.Config = Config;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetConfigRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iis.fraunhofer.de/kom/abt/wsn/SensorValues", Order=0)]
        public NodeDiscovery.SensorValuesFH.Configuration Config;
        
        public SetConfigRequest() {
        }
        
        public SetConfigRequest(NodeDiscovery.SensorValuesFH.Configuration Config) {
            this.Config = Config;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SensorValuesChannel : NodeDiscovery.SensorValuesFH.SensorValues, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SensorValuesClient : System.ServiceModel.ClientBase<NodeDiscovery.SensorValuesFH.SensorValues>, NodeDiscovery.SensorValuesFH.SensorValues {
        
        public SensorValuesClient() {
        }
        
        public SensorValuesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SensorValuesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SensorValuesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SensorValuesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.SensorValuesFH.GetSensorValuesResponse NodeDiscovery.SensorValuesFH.SensorValues.GetSensorValues(NodeDiscovery.SensorValuesFH.GetSensorValuesRequest request) {
            return base.Channel.GetSensorValues(request);
        }
        
        public NodeDiscovery.SensorValuesFH.Series GetSensorValues() {
            NodeDiscovery.SensorValuesFH.GetSensorValuesRequest inValue = new NodeDiscovery.SensorValuesFH.GetSensorValuesRequest();
            NodeDiscovery.SensorValuesFH.GetSensorValuesResponse retVal = ((NodeDiscovery.SensorValuesFH.SensorValues)(this)).GetSensorValues(inValue);
            return retVal.Series;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.SensorValuesFH.GetConfigResponse NodeDiscovery.SensorValuesFH.SensorValues.GetConfig(NodeDiscovery.SensorValuesFH.GetConfigRequest request) {
            return base.Channel.GetConfig(request);
        }
        
        public NodeDiscovery.SensorValuesFH.Configuration GetConfig() {
            NodeDiscovery.SensorValuesFH.GetConfigRequest inValue = new NodeDiscovery.SensorValuesFH.GetConfigRequest();
            NodeDiscovery.SensorValuesFH.GetConfigResponse retVal = ((NodeDiscovery.SensorValuesFH.SensorValues)(this)).GetConfig(inValue);
            return retVal.Config;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NodeDiscovery.SensorValuesFH.GetConfigResponse NodeDiscovery.SensorValuesFH.SensorValues.SetConfig(NodeDiscovery.SensorValuesFH.SetConfigRequest request) {
            return base.Channel.SetConfig(request);
        }
        
        public void SetConfig(ref NodeDiscovery.SensorValuesFH.Configuration Config) {
            NodeDiscovery.SensorValuesFH.SetConfigRequest inValue = new NodeDiscovery.SensorValuesFH.SetConfigRequest();
            inValue.Config = Config;
            NodeDiscovery.SensorValuesFH.GetConfigResponse retVal = ((NodeDiscovery.SensorValuesFH.SensorValues)(this)).SetConfig(inValue);
            Config = retVal.Config;
        }
    }
}
